kind: pipeline
name: default

steps:
    - name: test
      image: python
      commands:
        - pip install -r requirements.txt
        - pytest
    - name: publish
      image: plugins/docker
      settings:
        repo: mneiding/drone_ci_test
        tags: [ "${DRONE_COMMIT_SHA:0:7}","latest" ]
        username:
            from_secret: DOCKERHUB_USERNAME
        password:
            from_secret: DOCKERHUB_PASSWORD
    - name: notify
      image: ciscosso/drone-webex-team
      pull: true
      room: "Drone Pipe Test"
      access_token:
        from_secret: TOKEN
      when:
        status: [ changed, failure, success ]
