kind: pipeline
name: default

steps:
    #- name: test
    #  image: python
    #  commands:
    #    - pip install -r requirements.txt
    #    - pytest
    #- name: publish
    #  image: plugins/docker
    #  settings:
    #    repo: mneiding/drone_ci_test
    #    tags: [ "${DRONE_COMMIT_SHA:0:7}","latest" ]
    #    username:
    #        from_secret: DOCKERHUB_USERNAME
    #    password:
    #        from_secret: DOCKERHUB_PASSWORD
    - name: notify
      image: plugins/webhook
      settings:
        urls: https://webexapis.com/v1/messages 
        content_type: application/json
        token_value:
            from_secret: TOKEN
        token_type: Bearer
        template: |
            {
                "roomId": "Y2lzY29zcGFyazovL3VzL1JPT00vOWY4ZmQwNzAtZjM1YS0xMWVhLThiMDktZDE1MjI0YTkyNjZl",
                "markdown": "Build #{{ build.number }} for {{ repo.name }} finished with status {{ build.status }} \n* **Commit:** {{ build.commit }} \n* **Author:** {{ build.author }}"
            }
