kind: pipeline
name: default

steps:
    #- name: test
    #  image: python
    #  commands:
    #    - pip install -r requirements.txt
    #    - pytest
    #- name: publish
    #  image: plugins/docker
    #  settings:
    #    repo: mneiding/drone_ci_test
    #    tags: [ "${DRONE_COMMIT_SHA:0:7}","latest" ]
    #    username:
    #        from_secret: DOCKERHUB_USERNAME
    #    password:
    #        from_secret: DOCKERHUB_PASSWORD
    - name: notify
      image: plugins/webhook
      environment:
        WEBEX_TOKEN: "test1245"
      settings:
        urls:  https://webhook.site/dc3531af-5998-4a5e-b105-37605df9663f 
        content_type: application/json
        headers:
            Authorization=Bearer ${WEBEX_TOKEN}
        template: |
            {
                "roomId": "Y2lzY29zcGFyazovL3VzL1JPT00vOWY4ZmQwNzAtZjM1YS0xMWVhLThiMDktZDE1MjI0YTkyNjZl"
                "markdown": "Hello from the build"
            }
